name: Cypress CI/CD Pipeline

on:
  push:                       # Run on every push
    branches:
      - "**"
  schedule:                   # Run every day at 12:00 PM (noon) UTC
    - cron: '0 0 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (use stable version for Cypress)
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2   

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        env:
          # Optional: reduce flakiness for Electron runs
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
        run: |
          npx cypress run --browser chrome --headless

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
